"""Export COPY's current ACTIVE cluster wallets as the co-buyer AUDIT input list.

Prints the full `cluster_active_audit.txt` content (header + CSV rows) to stdout.
This is the INPUT browser-Opus works through in the active-list co-buyer audit
(bots/copy/discovery_automation/cluster_active_audit_prompt.txt) to decide, per
wallet, KEEP_ACTIVE vs PRUNE — the move to a co-buyer-only active list (cut Helius
cost; concentrate the list on wallets that actually form 3-wallet triggers).

Scoping (so the audit is safe + focused):
  - tier='active' only (those are the wallets billing Helius).
  - conviction-roster (conviction=true) and pinned wallets are EXCLUDED — they are
    exempt from the co-buyer rule (conviction is single-wallet by design; pinned is
    deliberately protected) and must never be pruned, so they aren't audited.
  - already_proven = YES if the wallet has ANY row in wallet_attributions (it has
    fired a real cluster in OUR data) -> browser-Opus auto-KEEPs it, no Birdeye
    needed. NO -> it actually gets audited on Birdeye for a co-buy pattern.

The list lives on Roy's OneDrive (browser-Opus reads it). Regenerate it by
ssh-running this on the server and writing stdout to the OneDrive file whenever
the active list changes materially.

Usage (in framework container):
  python -m scripts.export_active_audit_list
"""
from __future__ import annotations

from sqlalchemy import text

from framework.db import session_scope


HEADER = """# cluster_active_audit.txt — INPUT for the active-list CO-BUYER AUDIT
# ------------------------------------------------------------------
# COPY's current ACTIVE cluster wallets to audit for co-buyer participation
# (KEEP_ACTIVE vs PRUNE). Conviction-roster + pinned wallets are EXCLUDED (exempt
# from the co-buyer rule — never pruned, so not audited).
# already_proven=YES -> already fired a real cluster in our data (wallet_attributions):
#   auto KEEP_ACTIVE, NO Birdeye needed. NO -> audit on Birdeye per the prompt.
# HOW TO USE: bots/copy/discovery_automation/cluster_active_audit_prompt.txt
# AUTO-GENERATED by scripts/export_active_audit_list.py. Do not hand-edit.
# address,already_proven,attributed_cluster_pnl_usd,n_cluster_trades,note"""


def main() -> int:
    with session_scope() as s:
        rows = s.execute(text(
            """
            SELECT wp.address AS address,
                   CASE WHEN COUNT(wa.id) > 0 THEN 'YES' ELSE 'NO' END AS proven,
                   COALESCE(ROUND(SUM(wa.attributed_pnl_usd)::numeric, 2), 0) AS attr_pnl,
                   COUNT(wa.id) AS n
            FROM wallet_pool wp
            LEFT JOIN wallet_attributions wa ON wa.wallet_address = wp.address
            WHERE wp.tier = 'active'
              AND wp.chain = 'solana'
              AND COALESCE(wp.conviction, false) = false
              AND COALESCE(wp.pinned, false) = false
            GROUP BY wp.address
            ORDER BY proven DESC, attr_pnl DESC, wp.address
            """
        )).all()

    n_yes = sum(1 for r in rows if r.proven == "YES")
    print(HEADER)
    for r in rows:
        note = "fired in cluster(s) — auto-keep" if r.proven == "YES" else "audit on Birdeye"
        print(f"{r.address},{r.proven},{r.attr_pnl},{r.n},{note}")
    # trailing comment summary (ignored as a '#' line by readers)
    print(f"# total={len(rows)}  already_proven(YES,auto-keep)={n_yes}  "
          f"to_audit(NO)={len(rows) - n_yes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
