"""Export COPY's ACTIVE cluster wallets as the COST-RANKED co-buyer audit input.

Prints the full `cluster_active_audit.txt` content (header + CSV rows) to stdout.
This is the INPUT browser-Opus works through in the active-list co-buyer audit
(bots/copy/discovery_automation/cluster_active_audit_prompt.txt) to decide, per
wallet, KEEP_ACTIVE vs PRUNE — the move to a co-buyer-only active list.

KEY FINDING (2026-06-29) that shapes this: Helius cost is ~90% concentrated in ~20
wallets (top 10 = 69% of 30d deliveries, top 20 = 87%). Deliveries ARE the cost. So
we DON'T audit a flat 241 — we cost-RANK and audit the top ~20-30; pruning the
high-volume non-co-buyers there captures almost all the savings, and the low-volume
tail (incl. dormant/slow monthly teams) is ~free to leave active.

Per-wallet classification:
  - conviction-roster + pinned EXCLUDED (exempt; never pruned).
  - already_proven column:
      YES    = fired a real cluster (wallet_attributions) AND earns its cost
               (low volume OR net-positive attribution) -> auto KEEP_ACTIVE, no Birdeye.
      REVIEW = proven BUT high-volume (events_30d >= HIGH_VOL) AND net-NEGATIVE
               attribution -> audit DESPITE proven: a few-hundred-deliveries/day wallet
               that fired one losing cluster may be an MM bot, not a real recurring
               co-buyer. The +$533 trio (positive) stays YES; the -$25 MM-ish trio -> REVIEW.
      NO     = never fired a cluster -> audit on Birdeye.
  - priority (recency, from ~30d wallet_events_log): HOT(<=7d)/WARM(8-30d)/COLD(no
    event 30d = dormant, ~no cost, maybe a slow team -> LEAVE ACTIVE, don't prune).

Ordering: audit-needed rows (NO + REVIEW) FIRST by events_30d DESC (cost — money first);
auto-keep (YES) rows last. browser-Opus works the top and stops after 1-2 runs.

Usage (in framework container):
  python -m scripts.export_active_audit_list
"""
from __future__ import annotations

from sqlalchemy import text

from framework.db import session_scope

# events_30d at/above this = "high Helius cost" (MM/HFT-ish volume). A PROVEN wallet
# this busy is only auto-kept if its attribution is net-positive; otherwise -> REVIEW.
HIGH_VOL = 5000


HEADER = """# cluster_active_audit.txt — COST-RANKED INPUT for the active-list CO-BUYER AUDIT
# ----------------------------------------------------------------------------------
# COPY's ACTIVE cluster wallets to audit KEEP_ACTIVE-vs-PRUNE on co-buyer participation.
# Conviction-roster + pinned EXCLUDED (exempt — never pruned).
# Helius cost is ~90% in the top ~20 wallets, so this is SORTED COST-FIRST: audit-needed
# rows by events_30d DESC at the TOP, auto-keep rows at the bottom. Work the top, stop
# after 1-2 runs — pruning the high-volume non-co-buyers there captures most of the saving.
# already_proven: YES = fired a cluster AND earns its cost -> auto KEEP_ACTIVE, no Birdeye.
#   REVIEW = proven but high-volume + net-NEGATIVE -> audit DESPITE proven (MM bot or real
#   recurring co-buyer?). NO = never fired a cluster -> audit on Birdeye.
# priority: HOT(<=7d)/WARM(8-30d)/COLD(no event 30d = dormant, ~no cost, maybe a slow
#   monthly team -> LEAVE ACTIVE, don't prune). events_30d ~ that wallet's monthly cost.
# HOW TO USE: bots/copy/discovery_automation/cluster_active_audit_prompt.txt
# AUTO-GENERATED by scripts/export_active_audit_list.py. Do not hand-edit.
# address,already_proven,attributed_cluster_pnl_usd,n_cluster_trades,last_event_days,events_30d,priority,note"""


_SQL = text(
    """
    WITH ev AS (
        SELECT wallet_address,
               MAX(event_at) AS last_event,
               COUNT(*) FILTER (WHERE event_at > now() - interval '30 days') AS ev30
        FROM wallet_events_log
        GROUP BY wallet_address
    ),
    base AS (
        SELECT wp.address AS address,
               COUNT(wa.id) AS n_clu,
               COALESCE(ROUND(SUM(wa.attributed_pnl_usd)::numeric, 2), 0) AS attr_pnl,
               MAX(ev.last_event) AS last_event,
               COALESCE(MAX(ev.ev30), 0) AS ev30
        FROM wallet_pool wp
        LEFT JOIN wallet_attributions wa ON wa.wallet_address = wp.address
        LEFT JOIN ev ON ev.wallet_address = wp.address
        WHERE wp.tier = 'active'
          AND wp.chain = 'solana'
          AND COALESCE(wp.conviction, false) = false
          AND COALESCE(wp.pinned, false) = false
        GROUP BY wp.address
    )
    SELECT address, attr_pnl, n_clu, ev30,
           CASE WHEN last_event IS NULL THEN NULL
                ELSE EXTRACT(day FROM (now() - last_event))::int END AS last_event_days,
           CASE
               WHEN n_clu = 0 THEN 'NO'
               WHEN ev30 >= :hv AND attr_pnl <= 0 THEN 'REVIEW'
               ELSE 'YES'
           END AS proven,
           CASE
               WHEN last_event IS NULL OR last_event < now() - interval '30 days' THEN 'COLD'
               WHEN last_event >= now() - interval '7 days' THEN 'HOT'
               ELSE 'WARM'
           END AS priority
    FROM base
    ORDER BY
        CASE WHEN n_clu > 0 AND NOT (ev30 >= :hv AND attr_pnl <= 0) THEN 1 ELSE 0 END,
        ev30 DESC,
        last_event DESC NULLS LAST,
        address
    """
)


def _note(proven: str, priority: str) -> str:
    if proven == "YES":
        return "auto-keep (proven, earns its cost)"
    if proven == "REVIEW":
        return "proven but high-cost + net-negative — re-audit (real co-buyer or MM?)"
    return {
        "HOT": "active+costly — audit first",
        "WARM": "recently active — audit after HOT",
        "COLD": "dormant ~no cost / maybe slow team — leave active, don't prune",
    }[priority]


def main() -> int:
    with session_scope() as s:
        rows = s.execute(_SQL, {"hv": HIGH_VOL}).all()

    from collections import Counter
    buckets: Counter = Counter()
    total_ev = sum(int(r.ev30) for r in rows) or 1
    audit_rows = [r for r in rows if r.proven != "YES"]  # already cost-sorted first
    cum_top20 = sum(int(r.ev30) for r in audit_rows[:20])

    print(HEADER)
    for r in rows:
        buckets[r.proven] += 1
        led = "" if r.last_event_days is None else r.last_event_days
        print(f"{r.address},{r.proven},{r.attr_pnl},{r.n_clu},{led},{r.ev30},"
              f"{r.priority},{_note(r.proven, r.priority)}")
    print(f"# total={len(rows)}  auto_keep(YES)={buckets['YES']}  "
          f"audit_NO={buckets['NO']}  audit_REVIEW={buckets['REVIEW']}")
    print(f"# top-20 audit-needed = {cum_top20}/{total_ev} deliveries "
          f"({100*cum_top20//total_ev}% of cost) — auditing them is the bulk of the win")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
