"""Export COPY's ACTIVE cluster wallets as the DATE-WEIGHTED co-buyer audit input.

Prints the full `cluster_active_audit.txt` content (header + CSV rows) to stdout.
This is the INPUT browser-Opus works through in the active-list co-buyer audit
(bots/copy/discovery_automation/cluster_active_audit_prompt.txt) to decide, per
wallet, KEEP_ACTIVE vs PRUNE — the move to a co-buyer-only active list (cut Helius
cost; concentrate the list on wallets that actually form 3-wallet triggers).

Scoping + date-weighting (browser-Opus only does ~10-15 wallets/run and can't see
far back on Birdeye, so we PRIORITIZE — we do NOT audit a flat list of 241):
  - tier='active' only. conviction-roster + pinned are EXCLUDED (exempt; never pruned).
  - already_proven = YES if the wallet is in wallet_attributions (fired a real cluster
    in OUR data) -> auto KEEP_ACTIVE, no Birdeye. NO -> audit on Birdeye.
  - DATE-WEIGHT from wallet_events_log (~30d of webhook deliveries; deliveries ARE the
    Helius cost): each wallet gets last_event_days + events_30d + a priority bucket:
      HOT  = event within 7d  -> most recently active AND highest current Helius cost;
             auditable on Birdeye; audit FIRST (a HOT wallet that turns out NOT to
             co-buy is the expensive dead weight -> the biggest prune win).
      WARM = event within 8-30d -> audit after HOT.
      COLD = no event in 30d -> dormant: ~no current Helius cost, and may be a SLOW
             team between cycles (Roy: some teams fire once a month or two). LEAVE IT
             ACTIVE by default — do NOT prune COLD wallets; audit only if budget remains.
  Order: proven first, then HOT, WARM, COLD; within a bucket, most events first (most
  cost at stake). browser-Opus works top-down and stops when it's found enough co-buyers.

Regenerate by ssh-running this on the server and writing stdout to the OneDrive file.

Usage (in framework container):
  python -m scripts.export_active_audit_list
"""
from __future__ import annotations

from sqlalchemy import text

from framework.db import session_scope


HEADER = """# cluster_active_audit.txt — DATE-WEIGHTED INPUT for the active-list CO-BUYER AUDIT
# ----------------------------------------------------------------------------------
# COPY's ACTIVE cluster wallets to audit KEEP_ACTIVE-vs-PRUNE on co-buyer participation.
# Conviction-roster + pinned wallets are EXCLUDED (exempt — never pruned).
# already_proven=YES -> fired a real cluster in our data (wallet_attributions): auto
#   KEEP_ACTIVE, NO Birdeye. NO -> audit on Birdeye.
# priority (from ~30d of Helius deliveries = the per-wallet cost): HOT=active in 7d
#   (audit FIRST — most cost, Birdeye can see it); WARM=8-30d; COLD=no event in 30d
#   (dormant, ~no cost, MAYBE a slow monthly team -> LEAVE ACTIVE, do NOT prune).
# Work TOP-DOWN; stop when you've found enough co-buyers. events_30d ~ that wallet's
# monthly credit cost (a high-events wallet that doesn't co-buy = the dead weight to cut).
# HOW TO USE: bots/copy/discovery_automation/cluster_active_audit_prompt.txt
# AUTO-GENERATED by scripts/export_active_audit_list.py. Do not hand-edit.
# address,already_proven,attributed_cluster_pnl_usd,n_cluster_trades,last_event_days,events_30d,priority,note"""


_SQL = text(
    """
    WITH ev AS (
        SELECT wallet_address,
               MAX(event_at) AS last_event,
               COUNT(*) FILTER (WHERE event_at > now() - interval '30 days') AS ev30
        FROM wallet_events_log
        GROUP BY wallet_address
    ),
    base AS (
        SELECT wp.address AS address,
               CASE WHEN COUNT(wa.id) > 0 THEN 'YES' ELSE 'NO' END AS proven,
               COALESCE(ROUND(SUM(wa.attributed_pnl_usd)::numeric, 2), 0) AS attr_pnl,
               COUNT(wa.id) AS n,
               MAX(ev.last_event) AS last_event,
               COALESCE(MAX(ev.ev30), 0) AS ev30
        FROM wallet_pool wp
        LEFT JOIN wallet_attributions wa ON wa.wallet_address = wp.address
        LEFT JOIN ev ON ev.wallet_address = wp.address
        WHERE wp.tier = 'active'
          AND wp.chain = 'solana'
          AND COALESCE(wp.conviction, false) = false
          AND COALESCE(wp.pinned, false) = false
        GROUP BY wp.address
    )
    SELECT address, proven, attr_pnl, n,
           CASE WHEN last_event IS NULL THEN NULL
                ELSE EXTRACT(day FROM (now() - last_event))::int END AS last_event_days,
           ev30,
           CASE
               WHEN last_event IS NULL OR last_event < now() - interval '30 days' THEN 'COLD'
               WHEN last_event >= now() - interval '7 days' THEN 'HOT'
               ELSE 'WARM'
           END AS priority
    FROM base
    ORDER BY proven DESC,
        CASE
            WHEN last_event IS NULL OR last_event < now() - interval '30 days' THEN 2
            WHEN last_event >= now() - interval '7 days' THEN 0
            ELSE 1
        END,
        ev30 DESC,
        last_event DESC NULLS LAST,
        address
    """
)

_NOTE = {
    ("YES", "any"): "fired in cluster(s) — auto-keep",
    ("NO", "HOT"): "active+costly — audit first",
    ("NO", "WARM"): "recently active — audit after HOT",
    ("NO", "COLD"): "dormant ~no cost / maybe slow team — leave active, don't prune",
}


def main() -> int:
    with session_scope() as s:
        rows = s.execute(_SQL).all()

    from collections import Counter
    buckets = Counter()
    print(HEADER)
    for r in rows:
        if r.proven == "YES":
            note = _NOTE[("YES", "any")]
            buckets["proven"] += 1
        else:
            note = _NOTE[("NO", r.priority)]
            buckets[r.priority] += 1
        led = "" if r.last_event_days is None else r.last_event_days
        print(f"{r.address},{r.proven},{r.attr_pnl},{r.n},{led},{r.ev30},{r.priority},{note}")
    print(f"# total={len(rows)}  proven_auto_keep={buckets['proven']}  "
          f"HOT={buckets['HOT']}  WARM={buckets['WARM']}  COLD={buckets['COLD']}  "
          f"(audit HOT+WARM first; COLD = leave active, don't prune)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
