"""Export COPY's ACTIVE, PROVEN cluster wallets as co-trader-walk anchors.

Prints the full `cluster_anchor_wallets.txt` content (header + CSV rows) to stdout.
A wallet is an anchor if it's tier='active' AND has POSITIVE attributed cluster
PnL (it has actually formed profitable 3-wallet co-buys for COPY). Walking these
anchors' co-traders is the PRIMARY cluster discovery route (see
bots/copy/discovery_automation/cluster_discovery_vetting_prompt.txt route 1).

The anchor file lives on Roy's OneDrive (browser-Opus reads it). The local daily
reconcile task regenerates it by ssh-running this on the server and writing stdout
to the OneDrive file — so the anchors stay current as the active list + attribution
evolve.

Usage (in framework container):
  python -m scripts.export_cluster_anchors
"""
from __future__ import annotations

from sqlalchemy import text

from framework.db import session_scope


HEADER = """# cluster_anchor_wallets.txt — ANCHORS for the CO-TRADER WALK (cluster discovery)
# ----------------------------------------------------------------------------
# COPY's ACTIVE, PROVEN cluster wallets (positive attributed cluster PnL — they've
# actually formed profitable 3-wallet co-buys). Their CO-TRADERS are the highest-
# value cluster candidates: skilled groups hunt the same setups together, and
# cluster needs wallets that ACTUALLY co-buy the same token in the same window.
# HOW TO USE: see route 1 in cluster_discovery_vetting_prompt.txt — walk each
# anchor's run-token co-buyers (same pre-breakout window), rank by recurrence.
# AUTO-GENERATED by scripts/export_cluster_anchors.py (daily). Do not hand-edit.
# address,attributed_cluster_pnl_usd,n_cluster_trades,note"""


def main() -> int:
    with session_scope() as s:
        rows = s.execute(text(
            """
            SELECT wp.address AS address,
                   COALESCE(ROUND(SUM(wa.attributed_pnl_usd)::numeric, 2), 0) AS attr_pnl,
                   COUNT(wa.id) AS n
            FROM wallet_pool wp
            JOIN wallet_attributions wa ON wa.wallet_address = wp.address
            JOIN trades t ON t.id = wa.trade_id
                         AND t.sim_metadata->>'strategy' = 'cluster'  -- post-reset cluster only
            WHERE wp.tier = 'active'
            GROUP BY wp.address
            HAVING COALESCE(SUM(wa.attributed_pnl_usd), 0) > 0
            ORDER BY attr_pnl DESC, n DESC
            """
        )).all()

    # Auto-detect co-cluster groups: wallets sharing identical (attr_pnl, n) almost
    # always co-bought the SAME trades (their fair 1/N shares match) -> same group.
    from collections import Counter
    grp = Counter((float(r.attr_pnl), int(r.n)) for r in rows)
    gid: dict[tuple[float, int], str] = {}
    nxt = ord("A")
    for key, cnt in grp.items():
        if cnt > 1:
            gid[key] = chr(nxt); nxt += 1

    print(HEADER)
    max_n = max((int(r.n) for r in rows), default=0)
    for r in rows:
        note_parts = []
        g = gid.get((float(r.attr_pnl), int(r.n)))
        if g:
            note_parts.append(f"co-cluster group-{g} (same trades)")
        if int(r.n) == max_n and max_n > 0:
            note_parts.append("richest co-trader vein")
        print(f"{r.address},{r.attr_pnl},{r.n},{';'.join(note_parts)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
